name: Dependency auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]' }}
    steps:
      - name: Enable auto-merge for Dependency PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}